_wandb:
    value:
        cli_version: 0.21.0
        e:
            ompeg6moigligg95rs6y2dgib48p1g2e:
                codePath: learning/train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "59311214592"
                email: tjrcjf410@snu.ac.kr
                executable: /home/ros/miniconda3/envs/mujoco/bin/python
                git:
                    commit: 60cf8430011da531e08ce95a6ea48a56e5fbad7c
                    remote: https://github.com/google-deepmind/mujoco_playground.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-055e979c-be98-4fb4-1b6d-a18734cc5a72
                host: DESKTOP-ENONDU4
                memory:
                    total: "16723951616"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31
                program: /home/ros/mujoco_playground/learning/train.py
                python: CPython 3.12.11
                root: /home/ros/mujoco_playground/learning
                startedAt: "2025-07-06T04:25:47.077990Z"
                writerId: ompeg6moigligg95rs6y2dgib48p1g2e
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 12
                - 45
                - 50
            "2":
                - 12
                - 45
                - 50
            "3":
                - 13
            "4": 3.12.11
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
