# defaults:
#     - override hydra/launcher: submitit_local

# environment
benchmark: dm_control
task: CheetahRun
obs: state
exp_name : test
# evaluation
checkpoint: ???
eval_episodes: 1
eval_pi: true
eval_value: true # evaluate value function approximation
eval_freq: 50000

#policy
policy : wdsac


#dynamics shift
dynamics_shift: true
dynamics_shift_type: stochastic  # or deterministic
eval_randomization : false
# logging
wandb_project: wdsac
wandb_entity: tjrcjf410-seoul-national-university
wandb_silent: false
use_wandb: false
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

#rambo

real_ratio : ???
rollout_length : ???
adv_weight : ???
batch_size : ???
rollout_batch_size : ???

